### ISSUE TITLE
camel case

### ISSUE THREAD

**Issue by hanFengSan** [Naereen/SublimeText3_SwitchDictionary#1]
I hope that can support camel case.......It's very necessary......

**Comment by Naereen** [comment]
Hi,
Sorry, I am not sure to understand what you mean: camel case for what?

**Comment by hanFengSan** [comment]
Just like this:
may be I wrote `SwitchDictionary` to `SwitchDcitionary`, this plugin cannot check out the error.

the name of vars in my projects is all named by `camel case` like  `switchDictionary`, so it is very necessary for me :)

**Comment by Naereen** [comment]
Oh OK.
Well, this is behavior has nothing to do with my plugin: the only thing this plugin does is turn on or off the spellcheck, and loads a different dictionary.

From my tests, no matter the English dictionary I chose, a word in camelCase will never be highlighted as a spelling mistake (at least in my ST3).
Try to disable the plugin, then restart your Sublime Text, and check if it detects a spelling mistake in, let say, your example `SwitchDcitionary` ? Mine does not.

**Comment by Naereen** [comment]
Maybe I can repeat it: the built-in spell-checking in ST (3, but probably also 2) is not as perfect as the ones we are used to.

Forking and trying to tweak my tiny plugin won't change that.

**Comment by hanFengSan** [comment]
oh :(

**Comment by hanFengSan** [comment]
thx
